# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Ivan Gabriele"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Passionate. Entrepreneur & Developer."

# Tagline near the site title
tagline: "Passionate. Entrepreneur & Developer."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://2018.ivangabriele.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Ivan Gabriele"
author_bio: "CEO of Inspired Beings.<br>Founder or European Dream,<br>Mars Jump and Coinboard.<br>Actually in Paris, I also lived in SÃ£o Paulo, Chicago and London. 15 years of work for more than 100 clients.<br>Occasional pianist and music composer. In love with argumentativeness, travels and surf."
author_url:  "http://www.ivangabriele.com"
author_location: "Paris, France"
author_image: /images/ivan-gabriele.png

# Sidebar Add banner
banner_url: "http://justgoodthemes.com"
banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "Ivan_Gabriele"
# facebook_username: "username"
googleplus_username: "+IvanGabriele"
github_username: "ivangabriele"
# codepen_username: "username"
# dribbble_uername: "username"
medium_username: "@ivan_gabriele"
# instagram_username: "username"
# pinterest_username: "username"
linkedin_username: "ivangabriele"
# weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
